[Database]
type = "mysql"
host = "localhost"
port = "3306"
dbname = "dudo"
password = "dudoadmin"             
username = "dudouser"

[Application]
# Default server listen host and port
listenAt = "127.0.0.1:8080"
# For generate jwt token 
token = "thisisonlyfortest" 
# temp folder for store upload file 
tempfolder = "temp"
# bucket prefix
bucket_prefix= "dudo"

# default user storage limit
# it could be 1TB，1GB, 100MB, 10MB etc... 
default_disk_limit="5GB"

default_profile_image="/images/default.jpg"

[Storage]
server = "localhost"
port = "9000"
access_key = "minio"
secret_key = "minio123"