[Database]
type = "mysql"
host = "localhost"
port = "3306"
dbname = "dudo"
password = "dudoadmin"             
username = "dudouser"

[Application]
# Default server listen host and port
listenAt = "127.0.0.1:8080"
# For generate jwt token 
token = "thisisonlyfortest" 


[Storage]
server = "localhost"
port = "9000"
access_key = "minio"
secret_key = "minio123"