[Database]
type = "mysql"
host = "localhost"
port = "3306"
dbname = "dudo-test"
password = "dudoadmin"             
username = "dudouser"

[Storage]
server = "localhost"
port = "9000"
access_key = "minio"
secret_key = "minio123"

[Application]
# Default server listen host and port
listenAt = "127.0.0.1:8080"
# For generate jwt token 
token = "thisisonlyfortest" 
# temp folder for store upload file 
tempfolder = "temp"
# bucket prefix
bucket_prefix= "dudotest"
default_disk_limit="5GB"
default_profile_image="/images/default.jpg"